### ISSUE TITLE
Crash with certain settings causing an Exception

### ISSUE THREAD

**Issue by Oldgam3r** [Xaymar/OBS-AMD-Advanced-Media-Framework#124]
OBS studio 0.16.3  starts ok , but when i start stream there is crush on AMD coding(plugin). Coding on CPU runs ok
[Crash 2016-11-04 00-34-09.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/570320/Crash.2016-11-04.00-34-09.txt)

**Comment by NickParks** [comment]
Same issue on the R9 390. 

My crash is: 
https://gist.github.com/SirNickParks/de4c65b46a62db5de0074ac4855ca383

**Comment by Xbye** [comment]
> Crash log:
> http://pastebin.com/CvZtZJXy
> 
> New OBS log:
> https://gist.github.com/anonymous/24a3acd467d1dde5ff707d033891a06d
> 
> Honestly not sure what's causing it.

I posted over at Issue https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/128 . I believe I found the culprit!

Try setting "profile level" to something rather than leaving it at "automatic". For example, 4.1 - Note that if you have a preset enabled (IE. Twitch) it won't let you change it right now.

**Comment by Xaymar** [comment]
Crash looks to be because of an invalid Profile Level being selected and the exception that should have caused it to quit vanishing into nothing. Will need to do additional testing here.

@Xbye Read the wiki about [Profile Levels](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Configuration#profile-profile-level) and what they support. Always use Automatic or you will end up with weird unexplainable things happening.

**Comment by Oldgam3r** [comment]
> ry setting "profile level" to something rather than leaving it at "automatic". For example, 4.1 - Note that if you have a preset enabled (IE. Twitch) it won't let you change it right now.

 true , u cant change this when preset is setup , u cant change bitrate to.

> Always use Automatic or you will end up with weird unexplainable things happening.

i use preset twitch so there is no way i can change manualy from automatic for exmaple to 4.1

**Comment by Xbye** [comment]
@Xaymar 

> Read the wiki about Profile Levels and what they support. Always use Automatic or you will end up with weird unexplainable things happening.

I use auto for recording (If I ever record with AMF). Doesn't Twitch recommended 4.1 for their streaming servers otherwise it might reject your ingest or not work in transcoding (IE. Mobile)?

**Comment by Xaymar** [comment]
No, Twitch "recommends" 4.2. Mobile devices all support up to 4.2, more modern ones even up to 5.1. 4.1 only supports 1920x1080@30, not 60, 4.2 supports 1920x1080@60.

**Comment by Xbye** [comment]
@Xaymar Ah alright. Thanks! Google has been useless to finding such things lately.
