### ISSUE TITLE
Midstream obs crash

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#145]
Was streaming w/o record
twitch preset with 48 fps.
OBS 0.16.5
Plugin: 1.4.1.5
Driver: 16.11.1

There's no crashlog recorded but there was a message that it stopped working because OBS did hang and didn't crash completely. I was unable to close it via task manager - it was there for like 2-3 minutes, but eventually it stopped itself.
https://drive.google.com/open?id=0Bz6nA_MiY6AWSUozaVdBQWlJZk0 - log (hope the right one, judging by the date) and memory dump.

**Comment by ghost** [comment]
Crash with the same symptoms happened here: https://obsproject.com/forum/threads/midstream-crash.57669/
It has a crashlog there.

**Comment by Xaymar** [comment]
Try 16.11.4 and report back.

**Comment by ghost** [comment]
https://drive.google.com/file/d/0Bz6nA_MiY6AWZndlTFZpbk9MU3M/view?usp=sharing
crash, log, dump.
Updated driver

**Comment by Xaymar** [comment]
Still the same crash :/

**Comment by ghost** [comment]
Well, I updated driver to 16.11.4

**Comment by Xaymar** [comment]
I'm aware. I was hoping that 16.11.4 would fix this crash, as it happens outside of my control. Guess we'll have to wait until 16.11.5 or higher.

**Comment by ghost** [comment]
I'll keep on using CPU encoding than. Can you please make a patreon post or comment here so I get notified about needing a new test?

**Comment by Xaymar** [comment]
Sure

**Comment by CKannas** [comment]
@Xaymar I've experienced a number of midstream crashes since 11th November and just realised after checking the crash logs that happens in the same dll.
I'm attaching the crash logs and obs logs to have a look at them if you like.

Crash Logs:
[Crash 2016-11-10 17-33-29.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614435/Crash.2016-11-10.17-33-29.txt)
[Crash 2016-11-12 19-13-33.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614436/Crash.2016-11-12.19-13-33.txt)
[Crash 2016-11-12 19-18-48.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614438/Crash.2016-11-12.19-18-48.txt)
[Crash 2016-11-12 19-41-28.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614440/Crash.2016-11-12.19-41-28.txt)
[Crash 2016-11-12 19-43-05.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614439/Crash.2016-11-12.19-43-05.txt)
[Crash 2016-11-12 21-17-37.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614437/Crash.2016-11-12.21-17-37.txt)
[Crash 2016-11-12 22-52-15.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614445/Crash.2016-11-12.22-52-15.txt)
[Crash 2016-11-12 23-15-20.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614441/Crash.2016-11-12.23-15-20.txt)
[Crash 2016-11-15 16-18-55.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614446/Crash.2016-11-15.16-18-55.txt)
[Crash 2016-11-22 10-36-49.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614444/Crash.2016-11-22.10-36-49.txt)
[Crash 2016-11-22 10-51-31.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614443/Crash.2016-11-22.10-51-31.txt)
[Crash 2016-11-22 17-24-43.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614442/Crash.2016-11-22.17-24-43.txt)
[Crash 2016-11-22 17-54-14.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614451/Crash.2016-11-22.17-54-14.txt)
[Crash 2016-11-24 20-16-35.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614450/Crash.2016-11-24.20-16-35.txt)
[Crash 2016-11-26 16-27-42.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614452/Crash.2016-11-26.16-27-42.txt)
[Crash 2016-11-26 18-05-00.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614447/Crash.2016-11-26.18-05-00.txt)
[Crash 2016-11-26 18-19-37.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614449/Crash.2016-11-26.18-19-37.txt)
[Crash 2016-11-26 18-46-55.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614448/Crash.2016-11-26.18-46-55.txt)
[Crash 2016-11-26 19-46-24.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614453/Crash.2016-11-26.19-46-24.txt)

OBS Logs:
[2016-11-22 16-22-52.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614455/2016-11-22.16-22-52.txt)
[2016-11-22 17-24-55.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614454/2016-11-22.17-24-55.txt)
[2016-11-22 17-54-22.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614456/2016-11-22.17-54-22.txt)
[2016-11-24 19-07-00.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614460/2016-11-24.19-07-00.txt)
[2016-11-24 20-16-44.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614461/2016-11-24.20-16-44.txt)
[2016-11-26 15-52-17.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614457/2016-11-26.15-52-17.txt)
[2016-11-26 16-28-00.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614458/2016-11-26.16-28-00.txt)
[2016-11-26 18-05-07.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614459/2016-11-26.18-05-07.txt)
[2016-11-26 18-19-45.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614462/2016-11-26.18-19-45.txt)
[2016-11-26 19-46-30.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/614463/2016-11-26.19-46-30.txt)

I know its a driver a issue but I share my logs for extra sample.

**Comment by Xaymar** [comment]
Merging this to #143.
