### ISSUE TITLE
VCESpeedTest HD 7730

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#156]
This is my result benchmarked on MSI R7730-1GD5V1
[VCESpeedTest_HD7730.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/621652/VCESpeedTest_HD7730.zip)
I saw that some resolution like 160x120 have speed preset slower than balanced and Quality preset

**Comment by Xaymar** [comment]
### Anomalies:
- Speed slower than Balanced & Quality (160x120, 240x160)

That are all the ones that I could find. This could be due to multiple reasons, for example slow GPU clock speed switching (insufficient PSU or failing PSU) or Disk speed not being good enough at first and going up over time.

I've added them to the wiki anyway, so thanks!
