### ISSUE TITLE
RX480 GPU Encoder overloaded and stream "refreshing"

### ISSUE THREAD

**Issue by JLNNN** [Xaymar/OBS-AMD-Advanced-Media-Framework#183]
Currently Installed OBS Version: 17.0.0 (windows)
Currently Installed Plugin Version: 1.4.3.4
Currently installed AMD Driver: 16.50.2011-161219a-309792E (latest)
Latest log file: [here](http://www.awesumdude.tv/files/log.txt)
Video: https://www.twitch.tv/derawesumdude/v/112100771

I tried different settings (default, some modifications) but it doesn't change anything and is hard to reproduce. Sometimes the stream is looking like it's refreshing (every 2 seconds?) and after I changed the bitrate settings live on stream, it seems to re-init and then the refreshes are gone (look at video on 2 hours 39 minutes 53 seconds). But today my stream was suddenly around 1fps - and the audio was fine (look at video on 6 minutes 8 seconds).

In that stream session I changed the settings a few times during being online. At first I thought my gfx card needs some time to work properly but it seems to be another problem.

Any help is appreciated, thank you :)

**Comment by Xaymar** [comment]
To the overloaded part, that is not visible in the log - there are some parts where the GPU encoder stalled and some parts where it quickly caught up with everything else again. Also you tried to change static properties during the encoding session, this doesn't work properly and can cause issues.

As for the refreshing, that is normal. There's not much you can do, this is a limitation of hardware encoders with this design.

Edit: One thing you can try is increasing the VBV Buffer Size. However that only has a temporary effect.

**Comment by JLNNN** [comment]
So do you think additional logs would help? Or is this a driver / AMD specific issue? What can I do to improve streaming quality without having to "change" my settings during a stream session? Because these problems seem to appear even if I use the very default twitch preset. I don't even understand why this is happening on the latest RX480 :(

**Comment by acp2** [comment]
The same thing is happening on my 260x with Xaymar's plugin and Relive. 
I get why they don't give a single crap about the 2-300 series (not really though since they're supported cards), but this happening on a 480 isn't acceptable.

**Comment by Xaymar** [comment]
> Or is this a driver / AMD specific issue?

It's neither. It's a firmware issue and this can only be "fixed" by introducing another layer of testing for bitrate. Pre-Analysis Pass will help here on RX 4xx and above and for VCE2 and VCE3 cards B-Frames will help since they can reference both the previous and next I/P-Frame. x264 would have the same issue if it distributed the bitrate similar to how the firmware does things right now. You can see the same happening on Nvidia and Intel hardware, not sure about Apple.

> What can I do to improve streaming quality without having to "change" my settings during a stream session?

- Reduce the QP range from 0-51 to 16-41.
- Enable HRD Compatibility.
- Use a Profile and Profile Level that allows more (ex: High 4.2)
- If supported, use B-Frames. Be aware that using B-Frames cuts the max fps by about ~33% for each quality setting.
- Experiment with the VBV Buffer Size and Fullness.
- Change your Keyframe Interval to 1 second or half a second. Will drastically reduce other frame quality though.
- RX 4xx: Experiment with Master view mode and Pre-Analysis + VBAQ.
- non-RX 4xx: Experiment with Master view mode and Intra-Refresh.

> The same thing is happening on my 260x with Xaymar's plugin and Relive , which I get why they don't give a single crap about (not really though since it's still a supported card), but this happening on a 480 isn't acceptable.

How is this relevant to this issue? If you want to vent your anger somewhere, I recommend Twitter or Reddit.

**Comment by JLNNN** [comment]
Yesterday I did a stream session (~ 14 hours) with updated settings and I didn't encounter any problems. You can find my settings attached. Do you think there are still improvements I can do?

Guess you can close this issue then :) THX!

![streamsettings](https://cloud.githubusercontent.com/assets/1099235/21750272/aa192f0e-d5af-11e6-8709-9d4287d3268e.jpg)

**Comment by Xaymar** [comment]
Yes, set VBV Buffer to Manual and use a Size equal ~for~to Bitrate.

**Comment by JLNNN** [comment]
I think the quality didn't improve, but the last times that I streamed DayZ (a game with very many details like grass and trees) I realized that my webcam gets blurry all the time because the encoder uses almost everything of the bitrate available for the game and "ignores" the low motion webcam.
So I switched back to [CPU encoding](https://www.twitch.tv/derawesumdude/v/114273077) (which I don't really enjoy) with 2800 kbit/s and a veryfast preset. Do you think there will be comparable quality results with GPU encoding in the near future?

Have a nice day and keep up the great work!

**Comment by Xaymar** [comment]
Well, I already gave you everything that is necessary for better overall quality (primarily preanalysis pass and Intra-Refresh). Anything else is up to AMD. With HEVC we'll definitely see much better GPU encoding quality.

**Comment by Xaymar** [comment]
I'll close this as somewhat solved and at the same time merge it with #180 because it's the same stream refreshing issue.
