### ISSUE TITLE
Automatic strictness value not working as intended

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#198]
Hi,

first of all, thanks for the plugin and the time you have put into this project. 

So yesterday I got a complain that my stream on twitch has to buffer very often. I found out using https://r-1.ch/analyzer that my bitrate was very unstable. After that I monitored my upload bandwidth using the task manager and Obs Studio's current bitrate output. And indeed there where certain spikes if you switched from a very complex scene to a completely black scene and back.  
Then I found out about the "VBV Buffer" and "VBV Buffer Strictness" settings. So I played around with them. Setting the values to 0, 50, 100 and trying to deduce any abnormalities. I couldn't quite figure out the cause of the issue but the only setting which yields a **truly constant bitrate with less than 5-10kbps deviance** is by setting the VBV Buffer Strictness to **"0.5"**. 
Using "0.0" seems to ignore the filler data property because a black screen causes the rate to drop to almost 100kbps but stays below the CBR rate. 
Using "1.0" has a deviance of 50-75kbps and stays near the CBR rate.
Using "50.0" has a deviance of 200-500kbps and stays near the CBR rate. -> **Default value for all users**
Using "100.0" has a deviance of 1000-2000kbps and drops even to 100kbps on a blank screen.

During testing I used a CBR rate of 3500kbps using the twitch preset and left all other values at their default values. According to the log I have the following version: [AMF Encoder] Version 1.4.3.8 loaded (Compiled: 1.3.0.5, Runtime: 1.4.0.0, Library: 1;4;0;0;1.2;201701251759)
Hardware: RX 480

I think this is a very critical bug if somebody wants to stream to twitch. According to the twitch broadcast settings [Twitch Broadcast settings](https://help.twitch.tv/customer/portal/articles/1253460-broadcast-requirements):

> Variable bitrate is bad for video over the internet due to how TCP (the internet protocol most streaming video uses) works, and you should use CBR whenever possible.

I hope this is of any help to you. If you have any question just hit me up.

**Comment by ghost** [comment]
My system settings: 
Radeon Software Version - 17.1.2
Radeon Software Edition - Crimson ReLive
Graphics Chipset - Radeon (TM) RX 480 Graphics
Memory Size - 8192 MB
Memory Type - GDDR5
Core Clock - 1266 MHz
Windows Version - Windows 10 (64 bit)
System Memory - 32 GB
CPU Type - Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz

**Comment by Xaymar** [comment]
First I'd like to clarify that hardware encoding is not meant for streaming: It's primary use is zero-impact recording but it can be used for streaming if nothing else works. Also hardware encoding works differently from software encoding, it will try to compress to the Target Bitrate (using the VBV Buffer Size/Strictness as a guide) but if it can't do that it will overshoot/undershoot the Target Bitrate. Undershooting the Target Bitrate can usually be fixed by Filler Data, overshooting only by enabling Frame Skipping.

Now this doesn't explain why Filler Data breaks on your System, this is usually only happening with overclocked cards or broken driver installs. If you have an overclocked card (by vendor or yourself) always return to reference speeds first (610/910/1075/1145/1190/1235/1265 Mhz Core, 2000 Mhz Memory, Automatic Voltage). If that doesn't help or it isn't overclocked, use DDU to get rid of all AMD drivers (in Safe Mode) and then install the latest stable WHQL again.

I'll also explain how the Strictness value works. It defines the VBV Buffer Size and uses Target Bitrate, Peak Bitrate or QP values as guidelines (depending on Rate Control Method). At 0% it will use the maximum possible VBV Buffer Size, which practically removes any critical boundaries. At 50% it will use either Target Bitrate or Peak Bitrate (CBR or VBR). At 100% it will take the value from 50% and multiply it by 1/FrameRate, resulting in the strictest possible VBV Buffer Size. Needless to say each one has it's own problems: 0% may not hit the Bitrate but look great, 50% will vary around the Bitrate, 100% will severely undershoot the Bitrate unless there's need to go above and beyond.

It is up to you to decide what it will do if you do change the value. I recommend the following:

* Rate Control Method: VBR
* Target Bitrate: 2000kbit
* Peak Bitrate: 3000kbit (at least 500kbit below your maximum bandwidth)
* VBV Buffer Strictness: 50-75%
* VBV Buffer Initial Fullness: 90%

> Variable bitrate is bad for video over the internet due to how TCP (the internet protocol most streaming video uses) works, and you should use CBR whenever possible.

CBR (which is just VBR with Filler Data) has no advantage, no matter the network protocol used. The only thing that you'll do by enabling Filler Data is waste bandwidth that could have been used for other things - in fact you'll make buffering worse with Filler Data enabled.

Edit: By the way, 0.5% is equal to 0% due to rounding back to full kbit.

**Comment by Xaymar** [comment]
Tests with no blanking:

- 100%: Variation = ~5 kbit/s, Average = 3496 kbit/s
- 75%: Variation = ~350 kbit/s, Average = 3500 kbit/s
- 50%: Variation = ~420 kbit/s, Average = 3500 kbit/s (Average levels out after ~20 seconds)
- 25%: Variation = ~500 kbit/s, Average = ~3559 kbit/s, First second is ~4000 kbit above Target
- 0%: Variation = ~1000 kbit/s, Average = ~3378 kbit/s (Average levels out after a full minute)
- 0.5%: Identical to 0%

Tests with blanking:

- 100%: Blanking - Bitrate drops to 22 kbit/s; Stopping Blanking - High Bitrate Peak depends on time spent blanking
- 75%: Blanking - Bitrate at a perfect 3500 kbit/s; Stopping Blanking - Returns to normal bitrate variation
- 50%: Identical to 75%
- 25%: Blanking - Similar to 75%, drops to lowest possible bitrate for two seconds; Stopping Blanking - Identical to 75%
- 0%: Blanking - Drops to lowest possible bitrate for ~13 seconds otherwise identical to 75%; Stopping Blanking - ultra high bitrate peak depending on time spent blanking

Result at 100% is expected, the VBV Buffer is so small that Filler Data can't fill anything anymore - there's nothing left to fill (at 3500kbit 60 FPS, 100% means 59kbit VBV Buffer Size).

-----

As you can see, 50-75% is the sweet spot, with other values causing unknown effects. The Filler Data not being applied is likely due to the VBV Buffer Size being too large <50% (which goes towards maximum VBV Buffer Size) thus it covers much more than just a second or too small to have any effect >75% (which goes towards Bitrate * FPSDen / FPSNum. Perhaps @MikhailAMD can ask the Firmware team if my observation is correct.

**Comment by ghost** [comment]
Thank you for the very detailed explanation. I really appreciate it. 

> Now this doesn't explain why Filler Data breaks on your System, this is usually only happening with overclocked cards 

This was my issue. I didn't think this would make a difference. 
Thank you!

> First I'd like to clarify that hardware encoding is not meant for streaming: It's primary use is zero-impact recording but it can be used for streaming if nothing else works.

Why is that so? I compared recordings of x264 and AMD's hardware encoder over the past few days and couldn't quite get a satisfying result which comes near the quality of x264, especially in the lower bitrate spectrum of 1000-3000kbit at 720p@30. In my case, I have an i5 4670k and can barely record 720p at a decent quality setting without having to worry that the game which I'm streaming is occupying to much CPU resources. That's the reason why I turned to AMD's hardware encoder. Zero impact is really achieved and I'm really fond of that. If Twitch wouldn't limit the bitrate this much, my problem's wouldn't exist. On Youtube 720p@60 works great with the advised 6000kbps using AMD's hardware encoder.

**Comment by Xaymar** [comment]
> Why is that so?

Well, simply put it's because of what I already explained. They don't work like software encoders and have to work outside of everything else (except the GPU). Usually the chips and firmware on the encoding chip doesn't even get anywhere close to anything but ultrafast qualtiy (for both x264 and x265).

To my knowledge, the only HW encoder that does manage to get close to x264 veryfast is NVENC on GTX 950/960 (or something like that, there were special cards that had extra encoding features). Those cards provide rather incredibly quality, but they also have the nvidia price tag attached. Next up is AMF which produces quality between veryfast and ultrafast and then QSV which is usually worse than ultrafast on anything before Sky Lake.

Unfortunately unless we get actual access to the firmware source code, there is not much we can do here. x264 is this great because there have been many people working on it, implementing new things which makes the encoder better and better. HW encoding doesn't yet have this option. I'm hoping that in the future AMD may consider granting select people access to the firmware code, but I don't think this will happen.

**Comment by wazerstar** [comment]
One unique feature of the 960 is its new video engine that supports (HEVC) video decoding, unlike the 970 and 980 which only support encoding. This makes the 960 a great choice for home theatre PCs, 4K video can be decoded at low power. Naturally, there's support for HDCP 2.2 content over HDMI 2.0 too.

**Comment by Xaymar** [comment]
@wazerstar How is this relevant at all to this issue?

**Comment by wazerstar** [comment]
@Xaymar  you are talking about 960/950 the only unique feature it has is what I posted. So it does not have relevant to the hardware encoder you are talking about while ref: to nvidia 960/950?

**Comment by Xaymar** [comment]
No, the 950 and 960 had extra H264 features that resulted in better and faster encoding. This was nothing about HEVC decoding (why would the newer cards not be able to decode, decoding is the simple part).

**Comment by Xaymar** [comment]
Closing as solved since OP has not responded within 7 days and the issue seems to have been resolved.
