### ISSUE TITLE
CSGO Streaming with 144 hz feels like 120hz

### ISSUE THREAD

**Issue by aikuku** [Xaymar/OBS-AMD-Advanced-Media-Framework#206]
Hi, I'll try to describe my problem in short.

When i'm streaming CSGO with AMD H264 codec i feel that my monitor which is running at 144 refresh rate is refreshing at 120 hz or less. I've found information somewhere that i should set my fps at some integer fraction of 144 if i want to avoid it messing up my monitor hz. I've tried streaming at 48 fps, but it didn't feel right. Quick sync felt much better. Even though QS had bigger impact on CPU performance (game fps was lower, but gameplay felt smoother)

**My system specs:**
i5-4690k @ 4.4-4.6 Mhz
Asus Strix RX 470 @ 1,270 Mhz 
12 GB DDR3 RAM
Asrock z87 Mobo 

**OBS Settings:** 
Output rescale to 1280x720
Preset:Twitch 
Quality:Balanced
Bitrate: tried the range between 2000-3500
OpenCL:Enabled 

Output res: 720p 
Downscale filter: Bicubic 
FPS: 30, 36, 48, 60 (i'm about to try 72 right now).
Many thanks for your comments notes and suggestions.

**Comment by Xaymar** [comment]
The plugin itself has no measurable effect on Monitors, so what you're likely experiencing is lower frame rate in the game itself. And that is perfectly normal, since the plugin takes a small chunk of CPU power, a rather large chunk of PCI-E bandwidth and a medium chunk of GPU power away to do it's encoding task. Before you ask, no, none of those are optional, all of them are necessary to do the encoding work.

Please contact AMD and your Monitors manufacturer first before reporting non-measured issues. I can't work off of "but it feels like it's doing that" when it's not actually doing that.

**Comment by aikuku** [comment]
Thanks for the reply. I'm sorry didn't want to confuse you, just wanted to consult if you have had experience with something similar. Meanwhile I've found the solution - it seems that streaming fps has to be fraction of your monitor hz if you want to avoid GPU messing up your display hz. 

In 144hz case you must set FPS to 36 (144/4), 48(144/3) or 77(144/2), otherwise if you set fps to 30 or 60 your monitor will refresh at 120hz rate.

**Comment by Xaymar** [comment]
Sounds like you encountered the multi-monitor Hertz bug that has been reported multiple times - it's due to how Qt5 creates the Ui and related rendering Instances.

**Comment by Xaymar** [comment]
Attached the wontfix label as this isn't actually an issue with the plugin.
