### ISSUE TITLE
general behavior of IDR Period

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#218]
hi, i just want to ask why your plugin uses IDR Period of 1 -> its pretty useless -> should be between 1/3 - 1/5 of fps

and how does GOP calcs for different IDRs? because GOP gets pretty large in your plugin, even with small IDR Periods figures

so GOP of 1/2 fps and IDR Period of 1/5fps is pretty decent -> for 30fps it would be 15 frames per GOP and every 6th frame is an IDR frame (to flush b-frames (limited to 4 on vce 3.0)) -> so it should produce ipbbbipbbb and so on

ps IDR also makes some strange behavior when "search" through a video - usually with 2s keyframe it shouldnt take more then 2 secs when doing so to play the video - but it doesnt -> so you should fix that

**Comment by Xaymar** [comment]
The plugin does not use an IDR Period of 1. Here's the exact behaviour:

**AVC / H264**  
IDR Period in AVC is in **Frames** and if you use Keyframe Interval it is set to Keyframe Interval * Framerate rounded to the nearest integer. If you set it to 1 you can simulate Key-frame only content, such as MPEG-I or early reference encoders.

GOP is always the same as Framerate as defined by AMF, this is likely something @MikhailAMD and the Team behind AMF/VCE did to simplify logic.

**HEVC / H265**  
IDR Period in HEVC is in **GOPs**. 1 means one keyframe per GOP, 2 means one keyframe every 2nd GOP, and so on. If you do not override either IDR Period or GOP Size, the default for GOP Size is exactly the Framerate and IDR Period will be the rounded integer version of Keyframe Interval.

>ps IDR also makes some strange behavior when "search" through a video - usually with 2s keyframe it shouldnt take more then 2 secs when doing so to play the video - but it doesnt -> so you should fix that

This is a problem with how obs-studio mixes the content. It seems to match by audio timestamp (streaming) instead of video timestamp (rest of the entire recording software that ever existed). You can fix this by simply remuxing the file, ffmpeg will output proper timestamps then.

**Comment by Benman2785** [comment]
for h264:

mh, then i need to talk to AMD - because fps = gop isnt suitable for streaming -> but maybe improves quality for recording // but fps = gop is bad for scenes with heavy movement

and with "old" amf you had full control over gop & idr - but i know for the new u needed reveng to change that

with the current way of IDR-Period it is useless -> every 60 Frames an IDR is only usefull for slow movement scenes (like Hearthstone) - and it fucks up quality for fast scenes like most Shooters or many MoBas - same goes for GOP = FPS

and as i understand u use 2x GOP = IDR -> there really is no use for that in most streams - because it is very unlikely there is a reference used for up to 2s in a fast scene (what is 95% of games played) -> 0.5s is more realistic there

for h265:

different magic - but even there i would say "gop = idr = 1/2 fps" is pretty fine (note - better use of reference frames in h265)

//

mh, we should talk to OBS Devs to match it by video-timestamps -> anything else is pretty strange

**Comment by Benman2785** [comment]
![idr-period](https://cloud.githubusercontent.com/assets/21282980/24960586/821515aa-1f96-11e7-8f11-0a188a29ab3e.jpg)


here u see your auto-setting for IDR-Period in Master-mode (i know i wont get support for that) -> thats why i asked about its behavior - because when i use common values it has strange behavior for GOP and keyframes (but u said keyframe is a obs prob)

**Comment by Benman2785** [comment]
keyframe intervall with different IDR is fixed now with 1.9.9.11 (i can search through videos again)

**Comment by Xaymar** [comment]
> mh, then i need to talk to AMD - because fps = gop isnt suitable for streaming -> but maybe improves quality for recording // but fps = gop is bad for scenes with heavy movement

Well it isn't always GOP = FPS, it just picks whichever is lower. Example would be an IDR Period of 24 and a Framerate of 48 would give you an effective GOP (there is no metadata for this embedded) of 24.

> and with "old" amf you had full control over gop & idr - but i know for the new u needed reveng to change that

You actually did not have any control save for the metadata that programs read. If you checked with ffprobe, you could have seen that the GOP just continued until it hit the above boundary.

> with the current way of IDR-Period it is useless -> every 60 Frames an IDR is only usefull for slow movement scenes (like Hearthstone) - and it fucks up quality for fast scenes like most Shooters or many MoBas - same goes for GOP = FPS

When an IDR is placed depends entirely on the setting of IDR Period, which is controlled by Keyframe Interval.

> and as i understand u use 2x GOP = IDR -> there really is no use for that in most streams - because it is very unlikely there is a reference used for up to 2s in a fast scene (what is 95% of games played) -> 0.5s is more realistic there

No, I do not use that for H264. H264 control is simply IDR Period = Keyframe Interval * Framerate, so it is up to you to define what IDR Period will actually be. The default is simply 2 seconds, since most services perfer this.

An IDR Period that is lower than your Framerate will also result in drastic quality loss, since IDR frames terminate any ability to reference frames before it and then contain a full frame compressed so that it still fits in the average bitrate. Two I-Frames per second can easily fill up the entire average bitrate.

> different magic - but even there i would say "gop = idr = 1/2 fps" is pretty fine (note - better use of reference frames in h265)

The current way in H265 is doing well. Refer to my previous answer why 1/2 fps will result in less quality.

> mh, we should talk to OBS Devs to match it by video-timestamps -> anything else is pretty strange

I've talked to Jim about it, but nothing has come of it yet. Not sure what else to do, the timestamps I send back to OBS are quite literally as perfect as it gets.

**Comment by Benman2785** [comment]
> An IDR Period that is lower than your Framerate will also result in drastic quality loss, since IDR frames terminate any ability to reference frames before it and then contain a full frame compressed so that it still fits in the average bitrate. Two I-Frames per second can easily fill up the entire average bitrate.

you assume that the frames refer to eachother for 2s -> that is nearly impossible for 95% of games and scenarios -> those scenes change to fast for that -> maybe 10-20 frames can refer to eachother - 4 of them (in a row) bidirectional - but then the image still needs a p- or even an i-frame because it cant refer to other frames because the scene has changed -> and a GOP can contain more then 1 i frame at start

ps if you use minQP 22 (18 puts GPU under pressure - if i encode movies i use 20-22) and idr-period of 1/5 -1/3 fps it should improve quality with similar compression

as far as i know it improves quality if set correctly -> here an example video 720p@3500kbps: IDR is 6 or 10 and KeyFrameIntervall 2.0; minQP 22; maxQP 42; 

1/5 FPS = IDR -> not perfect, but okay in refresh time
http://benmanshafen.de/pics/OBS/Xaymar/30fps_idr-6_org.flv
1/3 FPS = IDR -> pretty decent quality, fits that game scenes very well
http://benmanshafen.de/pics/OBS/Xaymar/30fps_idr-10_org.flv

pps 1.9.9.11 hasnt fixed "search-bug" for videos -> video are orginal file

ppps - i speak ONLY ABOUT STREAMING - not local recording -> we both know that you need different settings for that; for local recording a big GOP with long IDR-Period is wonderfull - due to high bitrate for p and b frames

**Comment by MSxDOS** [comment]
> You can fix this by simply remuxing the file, ffmpeg will output proper timestamps then.

Does mkvmerge take care of that too?

**Comment by Benman2785** [comment]
@MSxDOS i will test that now

**Comment by Benman2785** [comment]
mkvmerge makes it worse xD - will upload video soon

edit: cool behavior when searching
http://benmanshafen.de/pics/OBS/Xaymar/30fps_idr-10_org.mkv

**Comment by Xaymar** [comment]
As this is pretty much what #220 describes, I'll close this.
