### ISSUE TITLE
Can't use OpenCL (Unknown reason)

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#230]
If I enabled OpenCL Transfer or Conversion, ffmpeg-mux64 say missing avcodec-57.dll, avutil-55.dll and avformat-57.dll but there is no file missing in OBS Studio.

**Comment by Xaymar** [comment]
Run Display Driver Uninstaller in Safe Mode, remove **ALL** GPU drivers (Intel, Nvidia, AMD), reboot, enter BIOS/UEFI, disable the Intel GPU in BIOS/UEFI, reboot, install AMD GPU Driver.

This entry is in the FAQ already: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-opencl-does-not-work

**Comment by max20091** [comment]
Tried reinstall Windows 10, disable iGPU and install AMD WHQL driver, still not working => this is not my error
Anyway, this is the log: https://gist.github.com/max20091/2eb66c75956d353611354a69ccf4bdf7
What I see here is: 07:34:28.509: [ffmpeg muxer: 'adv_file_output'] os_process_pipe_write for packet data failed which cause above issue

**Comment by Xaymar** [comment]
Then there is nothing I can do. The error with ffmpeg is known to be caused by Intel GPU drivers, which seem to still be loaded on your system. The only fix for you is to disable OpenCL features until you find out where they come from or actually follow the steps I told you to which was running DDU and not reinstalling Windows 10.

**Comment by max20091** [comment]
oh, Windows 10 auto install Intel GPU driver through Windows Update and I have to use DDU to uninstall it again, thanks for helping me :)
