### ISSUE TITLE
bitrate changes only set after OBS restart - Plugin v2.1.1

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#239]
Windows 10 Creators x64
AMD FX-9590
RX 480 8G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1670MHz CL9-9-9-27 (4x4G)

OBS 18.0.2
Plugin ver - 2.1.1
Drivers 17.5.1 (with Display-Color-Fix for additional Radeon Settings)

error:
[2017-05-09 18-01-11.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/987319/2017-05-09.18-01-11.txt)
after restart:
[2017-05-09 18-08-56.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/987328/2017-05-09.18-08-56.txt)

I installed latest Patreon-Build - recorded a video in 3500kbps; then changed bitrate to 5500 and started recording - but it stayed at 3500; changed it again to 5500kbps and started recording - still at 3500kbps - restarted OBS and then it sets bitrate correctly

btw - TheDivision is with the new Encoder from 17.5.1 so demanding that i HAVE to use constrained baseline - otherwise i would have "laggy game"

**Comment by Xaymar** [comment]
You didn't click Apply or OK:
[2017-05-10 08-40-52.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/988876/2017-05-10.08-40-52.txt)

**Comment by Benman2785** [comment]
believe me - i did...

**Comment by Xaymar** [comment]
Okay, then take a look at the log again. The following is done before you first start encoding:

```
18:03:22.845: Settings changed (outputs)
18:03:22.845: ------------------------------------------------
18:05:32.248: Settings changed (outputs)
18:05:32.248: ------------------------------------------------
18:05:39.744: Settings changed (outputs)
18:05:39.744: ------------------------------------------------
18:05:51.896: Settings changed (outputs)
18:05:51.896: ------------------------------------------------
```

Mind you, you actually started streaming, which enforces certain limits if the "enforce streaming service" box is checked. These may end up overwriting future settings as the OBS api for these is simply terrible and needs to be rewritten soon. And the next time you changed settings was while an encoding session was still active.

Just to make it clear, the plugin is not at fault here. The plugin has little control over what OBS gives it other than overriding the data sent to it and storing new data. Since I have been unable to reproduce this, I will still consider this invalid or a user error.

**Comment by Xaymar** [comment]
Thanks to #228, I have figured out what actually causes this. Hopefully the patch will fix this behavior.
