### ISSUE TITLE
Cannot find B-Picture Pattern setting.

### ISSUE THREAD

**Issue by win0na** [Xaymar/OBS-AMD-Advanced-Media-Framework#248]
I have noticeable blocky/pixelated output when encoding through this plugin, and the troubleshooting guide as well as a few closed issues in this issue tracker suggest setting the B-Picture Pattern setting to 0. However, I cannot find said setting despite setting the View Mode to the maximum value, and this issue is starting to become something of a pressing matter for me.

I have an MSI Armor RX 480, if that is any help. Thank you!

**Comment by Xaymar** [comment]
VCE1 and VCE 3.4 do not support B-Frames. Additionally:

Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by win0na** [comment]
Apologies, I expect you often come across people like me who do not read everything beforehand. Here's my specifications:

OS: Windows 10 Pro 64-bit
CPU: Intel Core i5 4690K @ 3.50GHz
RAM: 8GB Dual-Channel DDR3 @ 933MHz
Motherboard: MSI Z97S SLI Krait Edition
Graphics: 4096MB AMD Radeon RX 480
Storage: 250GB SSD, 1TB HDD
Audio: AMD High Definition Audio Device

OBS Version: 19.0.2
Plugin Version: 2.1.5
AMD Driver Version: 17.4.4
Log: [2017-05-23 14-51-48.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1023567/2017-05-23.14-51-48.txt)

VOD Link: https://www.twitch.tv/videos/146693858
Log: (same as the above?)

If the VCE version that is present on the RX 480 does not support B-Frames, is there any way for me to rid myself of the pixelated look? My target bitrate is 4000KB/s, with the quality preset set to Quality, downscaled to 720p.

**Comment by Xaymar** [comment]
I don't see anything out of the ordinary, except that you're using View Mode 'Master' which enables very unstable features.

Here's a few things you can try:
- Use View Mode Expert instead of Master
- Change the 'Downscale Filter' to Lanczos
- Change the Color Space from 601 to 709
- Change the Color Range from Partial to Full
- Change the Profile Level to 4.2 or higher
- Change the Profile to High
- Change Min QP to 21 or 23
- Enable Frame Skipping
- Use VBR instead of CBR

Aside from that i don'T know what else to suggest. A 1280x720 NV12 frame would require ~11.1mbit to be correctly represented without compression (or with the worst compressible image possible), so increasing the bitrate is probably the last option to test. Around 5.5 to 6 mbit should give you what you want.

**Comment by win0na** [comment]
The majority of those options have given me what I wanted. Thank you very much for putting up with me! :)
