### ISSUE TITLE
AMFSpeedTest FX-9800P

### ISSUE THREAD

**Issue by seronx** [Xaymar/OBS-AMD-Advanced-Media-Framework#250]
Hardware:
GPU: Radeon R7 9874BR
CPU: FX-9800P 2.3~3.8 GHz
RAM: 2 x 8 GB @ DDR4-1866

Software:
Radeon Software Version - 17.4.4 (APU)
Radeon Software Edition - Crimson ReLive
Windows Version - Windows 10 (64 bit) 15063.

[ResultsH264-R7Bristol.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1027917/ResultsH264-R7Bristol.zip)

If you need me to test anything, I'll be around.

**Comment by Xaymar** [comment]
Thank you for this, I appreciate it. I'm working on rewriting the wiki in order to be more readable in the future, so this might not be added immediately.

**Comment by DroWnThePoor** [comment]
@seronx Hi, this post caught my eye because I also have the FX9800P in a HP Envy notebook,
and I'm struggling to record with it.
What test is this exactly? I see that DirectX 11 is being used. I guess this plugin is Windows only, but what about the test?

I'm running OBS on a Ubuntu-Linux based system, and I can only use the soft encoder which I think is alot of what's holding me back, because  essentially my CPU is doing all the work and I have no hardware acceleration, correct?
At present I can't record a youtube video in a browser window capture unless I'm doing nothing but letting the video play, no multitasking at all.
I have it set to VeryFast 30fps canvas is 1920x1080 scaled output is 1280x720p.
I've never tried OBS on Windows 10, but it looks like Ubuntu's current open source amdgpu driver is crippled when running OBS.
I know we're on different OS, but any advice, insight, information would be greatly appreciated.

**Comment by Xaymar** [comment]
The AMF encoder is windows only, if you want to have Linux support please contact AMD.
