### ISSUE TITLE
2.1.3 - encoder overload

### ISSUE THREAD

**Issue by XeNz** [Xaymar/OBS-AMD-Advanced-Media-Framework#256]
**Software version:**
AMF encoder: 2.1.6 hotfix 3
AMD driver: 17.4.4 whql win10 64bit
OBS Studio: 19.0.2 windows x64

**PC specs:**
https://puu.sh/wi0eW/d08fe85547.png

I'm trying to stream 1536x864 (downscaled) @ 48FPS using your encoder. 
My card is a pretty old HD7850. The card is not being overclocked. During my streams it looks like the encoder cannot handle the load (-> "encoder overloaded"). Am I wrong trying to use these settings? Or is there something else going on?

View mode is on basic, output mode is on advanced. Twitch preset is being used and enforced. No settings except the bitrate were changed.. 

**Log file containing a few minutes of streaming:**
[2017-06-12 16-29-18.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1068521/2017-06-12.16-29-18.txt)

Stream recording:
https://www.twitch.tv/videos/151307472?t=02m20s

**Comment by Xaymar** [comment]
Analyzing the log shows more than one issue:

1. You have skipped frames due to rendering lag.
2. Audio buffering increased to over half a second.
3. OBS reports skipped frames due to encoding lag, but there's only one entry for AMF skipping frames in the log.

Problem 1 and 2 are very likely due to how you've set up your OBS, scenes and the game. First try to configure the game to the point where you get at least 1.3 times the monitor refresh rate in FPS, then limit the framerate to the monitor refresh rate (VSync helps here!). Additionally change downscaling from Lanczos to Bicubic and only use one game capture instead of seven.

Problem 3 is actually not really there. The plugin reports back one skipped frame due to encoder lag, but OBS reports 1919 skipped frames due to encoding lag - which is plain wrong. For the next log, turn on the "Debug" option in the AMF encoder so we can actually see what's going on.

**Comment by XeNz** [comment]
Cleared all my scenes. There's only one gamesource now. Changed to bicubic downscaling, switched to 1280x720 downscaling resolution instead of 1536x864. Still, there are _some_ frames being skipped 'due to encoding lag'. It also looks like there wasn't any additional audio buffering. Will try to post a log later with 100fps capped in-game. 

Log file:
[2017-06-13 12-57-06.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1072052/2017-06-13.12-57-06.txt)

Stream recording:
https://www.twitch.tv/videos/151524124?t=01m24s

**Comment by Xaymar** [comment]
The new log you uploaded is much better. In it you've only skipped 467 frames due to rendering lag and 189 frames due to encoding lag. However there isn't even the slightest sign of the encoder taking too long or the queue being locked too long. I'm pretty sure that OBS is bullshitting us here as the encoder did not have trouble keeping up even once.

Try the following, as i mentioned before:

>First try to configure the game to the point where you get at least 1.3 times the monitor refresh rate in FPS, then limit the framerate to the monitor refresh rate (VSync helps here!).

**Comment by Xaymar** [comment]
More than 7 days have passed since the last user interaction, so I will consider this solved.
