### ISSUE TITLE
AMFSpeedTest RX 550

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#270]
[AMF.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1215290/AMF.zip)

**Comment by max20091** [comment]
It seems RX 500 series is a little bit faster than RX 400 one in h265 benchmark

**Comment by Xaymar** [comment]
Differences in speed like this largely depend on GPU usage, memory clock and PCI-E bus width. I don't know what version of the test these were made with either - not that it really matters, the speed values will be reduced to one table on the Hardware Support page once I'm done remodeling the entire thing. Edit: This is for clarity reasons and so that people stop telling me that the plugin is shit because it can't reach those numbers. Of course it can't, there's a lot more going on with the plugin than in the benchmark.

**Comment by AMDJona** [comment]
Holy shit Nearly as fast as my Rx 580
