### ISSUE TITLE
Is there an issue with 2.3.1 and OBS 21.0.1?

### ISSUE THREAD

**Issue by razyogev** [Xaymar/OBS-AMD-Advanced-Media-Framework#294]
Updated to _OBS 21.0.1_ (64bit, windows) and latest plugin _2.3.1_ and encountered the following problem:
00:05:58.433: [AMF] Encountered Exception during AMF initialization: AMF Runtime Version is too old, please update your drivers. [_**NOTE: I do have the latest AMD driver version installed**_]
00:05:58.433: Failed to initialize module 'enc-amf.dll'

Downgraded to **2.2.4** and loaded properly
[AMF] Version 2.2.4 loaded (Compiled: 1.4.4.0, Runtime: 1.4.2.0, Library: 1;4;2;0;17.10.3211.1031;201707041820;CL#1429932).

Any suggestions?

**Comment by Xaymar** [comment]
Given by the log line you sent, the driver you have installed is not the latest driver. Since you are on 1.4.2.0 AMF, I can safely assume that you are using Windows 8 or another OS AMD no longer updates their drivers for. For your information, the latest driver is 18.1.x.

The 2.3.x releases have a blacklist in order to prevent users with driver too old from crashing during encoding, which has been the source of many support requests. So until the blacklist is lowered to allow 1.4.2.0 AMF (which might take a while), you either have to figure out how to use actually updated drivers (Win 7 and Win 8 should be able to use the same driver), down/upgrade to Windows 7 or 10, or install an older plugin version (2.2.4) that does not stop you from using crashy drivers.

**Comment by razyogev** [comment]
Thank you. You are correct. I was not aware of AMD's decision to halt Win 8.1 driver support

**Comment by Xaymar** [comment]
Blacklist will be reduced to a simple warning in an upcoming version.
