### ISSUE TITLE
Why not using the list from Wikipedia to list VCE capable HW ?

### ISSUE THREAD

**Issue by Kenshin9977** [Xaymar/OBS-AMD-Advanced-Media-Framework#319]
I see that you ask to make a test then submit an issue in order to add a given hardware to the Wiki.
Forgive me if I'm wrong but isn't a full list available on Wikipedia ?
By cross referencing the [APU's table](https://en.wikipedia.org/wiki/List_of_AMD_accelerated_processing_unit_microprocessors) with the [GPU's table](https://en.wikipedia.org/wiki/Radeon_HD_7000_Series) and the [VCE's table](https://en.wikipedia.org/wiki/Video_Coding_Engine#APUs) you theoretically have a complete list of VCE capable hardware and can use it to have a complete list on the Wiki. Sure you still need the issue system for the benchmark but the hardware capable part would be complete.
If you already knew that I'm curious to know why you haven't done that.

**Comment by Xaymar** [comment]
The test for the hardware is purely for the benchmark, **not** for getting the hardware listed as supported. The list of supported Hardware is already from Wikipedia.

**Comment by Kenshin9977** [comment]
Well the list isn't really complete then.
"Bristol Ridge" is a brand name, not the name of a specific device. The same goes for every other brand name.
"Raven ridge" isn't VCE capable but [has VCN 1.0](https://en.wikipedia.org/wiki/Unified_Video_Decoder#VCN_1) which adds a full hw VP9 decoder.

**Comment by Xaymar** [comment]
The wiki was last updated about 6 months ago. That is isn't really complete is kind of obvious for that. If you have any additions to make, please list them in full.

All Bristol Ridge APUs that i know of are capable of VCE 3.1, which makes them supported. Not all GPUs however have encoding capabilities, which is why they are listed individually. This is is visible on the three links links you yourself posted, but not always (there are per-vendor exceptions to this).

As for Raven Ridge, VCN 1.0 should be equivalent to UVD 7.0+VP9 and VCE 4.0, so they should be capable of encoding. I have no such hardware here so I can't actually test this.

**Comment by Kenshin9977** [comment]
I tested the Ryzen 2200G and it is capable of using your plugin on OBS.

About the APUs the Wikipedia article says that those from the Trinity Richland, Kaveri, Carrizo, Bristol Ridge, Kabini, Raven , Ridge, Temash, Beema, Mullins, Carrizo-L and Stoney Ridge families are VCE capable.
I made a [google sheet](https://docs.google.com/spreadsheets/d/1wfIskT12S5mtAWEt5hsLhX1JJOrwZtJtLm62_17hwuU/edit?usp=sharing) with every APUs and their GPUs when referenced of the Wikipedia article. 

We can see that for some APUs there is no IGP (e.g. the Athlon X4 940 from the Bristol Ridge family).
Also with some APUs there is only an "R5" mention wich means it has an AMD Radeon™ R5 Graphics but it doesn't says to us if it is VCE capable.

**Comment by Benman2785** [comment]
Athlon X4 940 is NO APU

last APU without VCE/AMF support are: Llano; Trinity; Richland (up to AX-6XXX)
working APUs with AMF are any higher than: AX-7XXX

**Comment by Xaymar** [comment]
You got APU and CPU confused here Kenshin9977, CPUs that have no IGP are not classified as APUs, so they are by default not supported. This much should be obvious by the definition of an APU, which is a CPU + an integrated GPU (or in mobile space also known as SoC).

Any APU is usually capable of UVD and most often also VCE. There are very few vendor exceptions and low-power models that do not have the VCE chip (or have it locked away with a custom vendor-specific firmware).

I'm still unsure what the actual problem is you're trying to show here. If the issue is that I don't list all APUs compared to all GPUs, then that is intended. There are far fewer APU exceptions compared to GPU exceptions and only in the later generations did this stabilize so that everything in GPU and APU space had similar capabilities.

**Comment by Kenshin9977** [comment]
About the difference between APU and CPU, it's obvious, I don't know why I said that.
About the list, I'm trying to make a script that detects if a computer has any hardware encoder available and if it's enabled. In order to do that I need a full list of AMD APUs that are VCE capable. I know this Wiki and thought that if you don't have the full list I could help by updating the Wiki. It's easier to check here rather than on the Wikipedia article if you just look for this specific bit of infomation.

**Comment by Xaymar** [comment]
You can just test if AMF can be initialized. If it can, UVD, VCE or VCN is available. If it can't, none of the three are available. The plugin itself for example does this, it launches an extra process that goes through the process of starting an encoder of every supported type. If something goes wrong (crash, freeze, etc) it won't list the encoder, same as if it wasn't supported. The same approach would work in nvenc and quicksync too, since they all only initialize if there's a supported GPU.

**Comment by Kenshin9977** [comment]
I agree and with AMD there is no other choice than to use this method.
But I also want to handle the case where the iGPU isn't enabled and to detect, with the CPU's name, if it's QuickSync / VCE capable. This way the people that don't know they have an iGPU could use it rather than to encode with their CPU since most computers can't handle a stream in x264 while playing on their PC.

**Comment by Xaymar** [comment]
Whitelisting by Vendor/Hardware/Subvendor Id is going to be a lot of data, just for the sake of telling the user something they should already know given they've bought the hardware in the first place. You'll likely find some incomplete Vendor+Hardware Id lists somewhere on the internet that you can source this data from, but otherwise will have to trust the result of testing UVD/VCE/VCN capabilities.
