### ISSUE TITLE
Bitrate keeps going up and down?

### ISSUE THREAD

**Issue by SOD96** [Xaymar/OBS-AMD-Advanced-Media-Framework#33]
Seen it go to the lows of 400 then spike up to 1200 when I start moving a lot.

I'd rather it stick within the 2000 range + Because it makes my stream look bad.

Any suggestions?

**Comment by razorlikes** [comment]
You are probably using VBR instead of CBR. Switch to CBR to use a constant bitrate.

**Comment by Xaymar** [comment]
If you are using CBR, this is normal since "Filler Data" stopped working properly - it will cap to the Target Bitrate if there's stuff going on. As for VBR (Peak constrained), it'll try to get to the target bitrate and will at most use the peak bitrate. VBR (Latency Constrained) completely depends on the load of the System and the latency (time required to encode).

**Comment by SOD96** [comment]
I changed to CBR and my quality went to absolute crap. Like really really bad....

**Comment by Xaymar** [comment]
Do set a correct bitrate. The Advanced encoder expects it in BITS (not kbits), the simple one in kbits

**Comment by SOD96** [comment]
Yup it sends at around 2500-4000 so that is fixed now. (KBITS)

But the quality is still really bad. Like I have 50 bitrate in there.

**Comment by wazerstar** [comment]
Number of b pictures 0

if you want 2500 its 2500000 and 40000 its 4000000

**Comment by Xaymar** [comment]
This will probably be fixed by the new AMF SDK. I'm closing this now as work on the Media SDK version has stopped.
