### ISSUE TITLE
Unable to set Profile Level on Vega APUs

### ISSUE THREAD

**Issue by LegendaryBrick** [Xaymar/OBS-AMD-Advanced-Media-Framework#345]
@Xaymar have recently come across several Hardware encoding issues with AMD Ryzen 2400g chips. Originally the AMD Hardware option did not appear. After doing a clean GPU uninstall and reinstall it did appear, only now when I try and go live an error appears. I chatted with the fine folks over on Discord and they directed me to you. Here is my log file. https://obsproject.com/logs/2mVepyVsL03Zu66G

**Comment by Benman2785** [comment]
"17:54:58.243: Running as administrator: false" - run as admin pls
"17:56:22.192: [AMF] [H264]<Id: 5> <Plugin::AMD::EncoderH264::SetProfileLevel> Failed to set to 31, error AMF_FAIL (code 1)" 

did set any preset in "Output" - try "twitch" pls

**Comment by LegendaryBrick** [comment]
@Benman2785 Tried both of those, no improvement. I will wait for @Xaymar 's answer.

**Comment by Xaymar** [comment]
I have seen this error appear recently, and it seems to be Vega 11 exclusive. ~~For whatever reason, the Vega 11 encoder does not support basic H264 encoding levels (3.1 and earlier) and instead fails. I believe this is a driver error, as the encoder will happily choose profile level 3.1 if it is not set for the same configuration.~~

This can be worked around in code by limiting the automatic profile level to supported values, if any are actually supported.

**Comment by Xaymar** [comment]
Please try one of the builds in this branch attempting to work around the issue: https://ci.appveyor.com/project/Xaymar/obs-studio-amf-encoder-plugin/builds/20208290/artifacts (.exe is installer, .zip/.7z are binary archives for manual extraction).

**Comment by LegendaryBrick** [comment]
@Xaymar I installed the builds and unfortunately received the same encoding error, if I installed the build correctly. Install the exe then extract the zip?
I believe I did as the text changed from AMD to (Hardware) AMD.
https://obsproject.com/logs/EukqbrXswD_Q88VE

**Comment by Benman2785** [comment]
did you try set a profile level higher than 3.1 - like 4.1?

**Comment by LegendaryBrick** [comment]
@Benman2785 Asking me?

**Comment by Benman2785** [comment]
yes - because: 

> I have seen this error appear recently, and it seems to be Vega 11 exclusive. For whatever reason, the Vega 11 encoder does not support basic H264 encoding levels (3.1 and earlier) and instead fails. I believe this is a driver error, as the encoder will happily choose profile level 3.1 if it is not set for the same configuration.
> 
> This can be worked around in code by limiting the automatic profile level to supported values, if any are actually supported.

**Comment by LegendaryBrick** [comment]
@Benman2785 Didn't notice that, tried that and it seems to be working! Set it to 4.1, and it now goes live. However there are new issues presented. I'll link the VOD asap, but looking at the output there seems to be encoding issues. Choppiness/Blur?

**Comment by Xaymar** [comment]
~~Yeah this is definitely a driver bug.~~ I've changed things to actually query the GPU/Driver for supported Profile Levels and it reports back 3.2 as supported - and then fails to set it anyway. ~~Please report this to AMD through their media channels and the bug report forum.~~

**Comment by LegendaryBrick** [comment]
@Xaymar Alright for now i'll try and attempt to downgrade to a previous driver version.

**Comment by Benman2785** [comment]
what bitrate do you use - and what image?
you cant compare that to a 3-pass x264 qp23 file - it needs more like 10x this bitrate ;)

**Comment by LegendaryBrick** [comment]
1080p 30fps 5500kbps

**Comment by Xaymar** [comment]
This seems to be a common occurrence only on Vega APUs, no other AMD product is affected yet by the same issue. The problem is that the hardware/driver reports back profile levels that it then fails to set, for an unknown reason. This leaves me with a few options:

1. Implement an additional option to just trust the driver with the profile level. Unfortunately in the past this has resulted in corrupted streams or Twitch just showing a black screen, which is why I've defaulted to a proper automatic profile level in the plugin.
2. ~~Get enough people behind this to make AMD aware of the issue, so that they have to fix it eventually. This might come over as unprofessional, but it is the only contact I have with AMD lately, as the AMF repository issues simply just sit there and collect dust.~~
3. Just tell users to change their Profile Level manually to some value that works with their APU/Driver. 
4. Edit: Move Resolution and FrameRate settings before Profile and ProfileLevel

~~Personally I'm a fan of 2 because it should get AMD to actually fix a bug in their stuff.~~ But right now I'm opting for 3, as 1 just opens up too many possibilities of people or AMD screwing up.

**Comment by Xaymar** [comment]
Those affected, please try [this build](https://ci.appveyor.com/project/Xaymar/obs-studio-amf-encoder-plugin/builds/21421480/artifacts). As always, .exe is the installer, .7z/.zip are archives for manual/portable installs.

This build moves the Resolution and FrameRate setting before Profile and Level, as @Mikhail_AMD instructed me to do. This is backwards from what it used to be, as earlier Drivers checked Profile and Level when setting Resolution and FrameRate, so I can give no guarantee that this actually works.

**Comment by Xaymar** [comment]
@LegendaryBrick If you still have that Vega APU, it would be very appreciated if you could try that build and report back.

**Comment by Alph4Bird** [comment]
> @LegendaryBrick If you still have that Vega APU, it would be very appreciated if you could try that build and report back.

Had the same problem as OP, using Vega 8 with Ryzen 2200g, and that build works perfectly fine now. Thanks so much!
