### ISSUE TITLE
Unknown Error Radeon RX 580

### ISSUE THREAD

**Issue by Raymaniac** [Xaymar/OBS-AMD-Advanced-Media-Framework#352]
Hi there,

I have tryed the plugin but it does not seem to work for me. There is always the "An unknown error occured" popup window coming up.
I installed the 2017 c++ Pack recommended on the your site and updated my graphics driver to the newest version.
Here also is the log output:
[2018-12-23 19-17-25.txt](https://github.com/obsproject/obs-amd-encoder/files/2706194/2018-12-23.19-17-25.txt)

I hope you can find the issue there, because I found nothing on the internet and don't have a big knowledge about this issue.

Best Regards

**Comment by Xaymar** [comment]
```
19:20:38.290: [ffmpeg muxer: 'adv_file_output'] Writing file 'D:/OBS_Aufnahmen/2018-12-23 19-20-38.mp4'...
19:20:38.513: [AMF] <Id: 6> Initial Frame Latency is 129509292 nanoseconds.
19:20:38.513: [ffmpeg muxer: 'adv_file_output'] os_process_pipe_write for info structure failed
19:20:38.513: [ffmpeg muxer: 'adv_file_output'] Output of file 'D:/OBS_Aufnahmen/2018-12-23 19-20-38.mp4' stopped
```

Doesn't look like the issue is because of the plugin. Did you check that your disk has enough space to store the video and that your OBS Studio installation is not corrupted?

**Comment by Raymaniac** [comment]
Hi,
Thanks for the quick reply.
Yes I tried different disks that all should have enough space left. I also run OBS in Administrator Mode to avoid permission issues.
Further I did multiple reinstalls of OBS and the plugin.
With other encoders, such as x264 or Intel QuickSync there are no issues, just with the AMd ones.
I also noticed another strange thing. If I run my recording with the AMD x264 encoder it does not work but if I run it with the x265 Encoder with a keyframe interval of 0 the recording starts but I am not able to stop it (OBS says "Stop recording..." but nothing happens). Maybe that helps you as well.

Could it also be an issue with my graphics card driver?

Best Regards.

**Comment by Xaymar** [comment]
It is possible that the issue is from your graphics driver. Unfortunately the log file does not reveal anything suspicious, and since OBS never wrote anything to disk this is impossible to debug. It'd be best to attempt a full clean reinstall using Display Driver Uninstaller.

**Comment by Raymaniac** [comment]
Okay thank you for you quick reply. I will take a look at my graphics driver and reply under this topic if I get any results, positive or negative :)

**Comment by toannguyen83** [comment]
Hi, I'm having similar issue with my RX 580. When I use AMD Hardware Encoder, I get the same error.
- See Log file: https://obsproject.com/logs/g9oAktZfxm8RQOP1
- I'm using Windows 10 64-bit, OBS 22.0.2 64-bit, AMD Driver 19.1.1
- Did DDU clean install
- Also did swap out to different disk output, same error

So right now I'm using the Software x264 encoder and it works fine. this isn't an issue when I used my gtx 1060 (with nv encoder). Not sure if something specific to this RX 580. Will keep posted if I found any workaround.

**Comment by Xaymar** [comment]
Please upload the output file too if there is one, I'm very curious as to why ffmpeg fails to write the info structure on the first output frame. @MikhailAMD might be interested in this too.

Edit: Also start OBS using the command line `--unfiltered_log --verbose`, and check the Debug flag in the expert view mode for the encoder if possible.

**Comment by toannguyen83** [comment]
@Xaymar Hi, here is the new output log file
[2019-01-24 10-51-06.txt](https://github.com/obsproject/obs-amd-encoder/files/2792706/2019-01-24.10-51-06.txt)
- I ran OBS with the above command line
- I switched the Output > Output mode to Advance, then on Recording Tab I set the Debug flag to true for the AMD H264 encoder.
- I also tried both AMD H264 and H265, same error.

Let me know if anything else I can provide.

Oh if you're looking for the actual video output file, it didn't create any.

**Comment by toannguyen83** [comment]
@Xaymar  and @Raymaniac 

I found this thread that someone reported with similar issue and has a workaround 
https://obsproject.com/forum/threads/solved-recording-unspecified-error-os_process_pipe_write-for-info-structure-failed.99027/

I was able to apply the workaround and I'm able to record using AMD Encoder now.
- I added `C:\Program Files\obs-studio\bin\64bit`  to **User Environment PATH variable** (probably work with System Environment too)
- Since I installed 64-bit version, thus the path is \bin\64bit 
- The thread mentioned some required DLLs that weren't loaded for ffmpeg and they are in obs-studio bin folder. I'm not fully understand the issue, perhaps you guys can visit the thread for more details.

**Comment by YellowOnion** [comment]
Why was this closed? My OBS (23.0.2) still has this error, and I shouldn't have to Google, and then mess around with path environment variables to get it to work.

**Comment by Benman2785** [comment]
@YellowOnion maybe the fix is ready but not released so far

**Comment by Xaymar** [comment]
The issue was closed because this is not a bug, crash or otherwise relevant to the plugin. It affects the ffmpeg muxing process, which is not provided by this plugin, and not maintained by the plugin maintainers either. The ffmpeg muxing process is part of OBS Studio.

If you need OBS Studio help, go to https://obsproject.com/ and either choose Discord or the Forum for help. Remember that every helper there is a volunteer.

> I shouldn't have to Google

If you want to solve a problem that is happening on your system, then you should have to Google a solution for it. Nobody else will do it for you unless you pay them to solve it for you. For example, start by figuring out which application you installed that messed with the ffmpeg binaries, causing OBS Studio to no longer work right.

**Comment by YellowOnion** [comment]
This bug was closed, with the status "solved", but it wasn't solved (I don't consider googling & manually editing PATH variables as user friendly solution, most users will just go install other software that just works), it still affects fresh installs of windows (like mine) and it's been reported multiple times in the forums, so I also doubt it's unique to my system.

I'm not demanding anyone fix it for me, it's just absurd to close an issue as solved, when it wasn't solved, I would have personally left it open until volunteers had found a better fix that didn't require googling (OBS could modify the PATH variable on install or at runtime for example). And reported it to the correct bug tracker.

**Comment by Xaymar** [comment]
As per my previous comment, this is not the bug tracker for OBS Studio, nor a forum for OBS Studio. Anything posted here has to be relevant to the AMD Encoder plugin, and as the plugin works just fine in all test VMs that I have, and it's also not the plugin that's breaking, I chose to mark this as solved and closed the issue.

If you have a problem with OBS Studio, you will need to go to https://obsproject.com/ and file it in the forum, or even their mantis bug tracker. This is not a bug with the plugin.

Locking because it's getting stupid.
