### ISSUE TITLE
[tracker] Linux support in 2020.

### ISSUE THREAD

**Issue by RarogCmex** [Xaymar/OBS-AMD-Advanced-Media-Framework#397]
### Description
The complete Linux support (all distribution). Gentoo linux e.g.
AMF is open-source and supports Linux now https://github.com/GPUOpen-LibrariesAndSDKs/AMF 

### System Information

rarogcmex@RarogCmexEngine ~ $ uname --all
Linux RarogCmexEngine 5.4.6-ck-RarogCmex #3 SMP PREEMPT Sun Jan 12 19:40:04 +05 2020 x86_64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz GenuineIntel GNU/Linux

### Checklist:

- [x] I have read the contribution guidelines.
- [x] This is not a bug, crash or generic issue.

**Comment by RarogCmex** [comment]
Please don't close its because it should be used as tracker for all Linux-related things

**Comment by Xaymar** [comment]
Linux support is not planned for this project. Please use alternatives like ffmpeg and VAAPI instead, which have much wider support.

**Comment by Xaymar** [comment]
See #335, #361. Unless someone else picks up Linux integration, nothing will change with that plan.

**Comment by RarogCmex** [comment]
Ok, so we should wait.
Well, but alternative -- obs ffmpeg encoder is dead, isnt it? I couldn't get it working.

**Comment by Xaymar** [comment]
obs-ffmpeg-encoder is merged into obs-streamfx. It still needs work, but at the moment I am prioritizing  paid work and secret projects.

**Comment by ogmkp** [comment]
Agree too, we need AMF plugin for Linux, because (or I don't know how to) we can't set preset profiles (quality, balanced, speed) in VAAPI way on OBS for a great video encoding offload.

**Comment by phaitonican** [comment]
Please someone add AMF, FFMPEG seems only record 1080p30fps on my mid range amd gpu.

**Comment by SchrodingerZhu** [comment]
any update recently?

**Comment by cprn** [comment]
There's [obs-studio-amf package](https://aur.archlinux.org/packages/obs-studio-amf) that used to work like a month or two ago but I just tried it and it doesn't compile. I didn't try to just bump up versions in PKGBUILD file because of the AUR comment:

> Since OBS 30.0 has been released, I'll close the package.
>
> The person who did the patch to enable AMF Encoding says that now the quality with FFMPEG has been fixed on AMD Cards (https://github.com/obsproject/obs-studio/pull/9179)
> 
> Since the MR in closed and the patch no longer maintained I would close this AUR package.

So it sounds like if someone was to update the patch for OBS 30, it'd be working.

I tried OBS 30 without the patch with [ffmpeg-obs](https://aur.archlinux.org/packages/ffmpeg-obs) and it works fine, I can record with HEVC Main and Main10 through VAAPI without issues - it's in Advanced view only, doesn't show in Simple.

**Comment by ogmkp** [comment]
That would be interesting, there's already nvenc.
The AMF encoder is only available with the amdgpupro driver while the free amdgpu driver is equally powerful or faster.
Is there really a benefit over VAAPI (cpu, gpu, bus loads)?

**Comment by Zeioth** [comment]
I've tested recording a video on arch Linux with AMF using the closed source AMD driver AMDGPU and it records correctly on OBS 

```sh
sudo pacman -S obs-studio
or 
paru -S obs-studio-git
```

![screenshot_2023-12-19_21-17-19_359222515](https://github.com/obsproject/obs-amd-encoder/assets/3357792/a1ac0692-d634-455d-9f9f-460100bc939f)

![screenshot_2023-12-19_21-15-36_062031893](https://github.com/obsproject/obs-amd-encoder/assets/3357792/6cfcc553-98f4-4d00-a68c-ae54e5254107)

## More info
* I can record correctly on 8 and 10 bits on hyprland (wayland).
* Note that you don't need to run the AMDGPU driver system wide. You can [install the driver in /opt/](https://github.com/Frogging-Family/amdgpu-pro-vulkan-only) and start OBS the next way even if your system is currently running the RADV driver, or any other.
```
AMD_VULKAN_ICD=RADV-PRO VK_ICD_FILENAMES=/opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd64.json obs
```

## What doesn't work yet
- I can't choose AMF for streaming. → Not a big deal because no streaming service support it yet anyway.

**Comment by 3laws** [comment]
> ```
> AMD_VULKAN_ICD=RADV-PRO VK_ICD_FILENAMES=/opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd64.json obs
> ```

Not working with 30.0.2-2, neither with git. Also running hyprland.

![image](https://github.com/obsproject/obs-amd-encoder/assets/4267075/b1af2c43-c1a0-4e34-b128-23f15f3090f7)

**Comment by cprn** [comment]
On Arch based distros there's AUR package `obs-studio-av1` that brings a patched version of latest OBS Studio, it supports FFmpeg AV1. Works fine on open driver.

**Comment by mirh** [comment]
Since [tuesday](https://github.com/obsproject/obs-studio/pull/8832) that's no longer necessary with `obs-studio-git`

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
