### ISSUE TITLE
My system H264 and H265 resultts

### ISSUE THREAD

**Issue by jaredn13** [Xaymar/OBS-AMD-Advanced-Media-Framework#438]
### Description

"If you have a GPU or APU with VCE support and it is not yet listed here or there are no limits for it known, you can [run the test yourself](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/download/1.9.9.6/AMFSpeedTest.zip)! Once you have run the test, create an issue and it will be added to the wiki."

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST] 23.5.2 (31.0.14057.5006)
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...] Windows 11 Pro 
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...] 22H2 22631.1900
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...] 7800X3D
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...] RX 7900 XTX
- RAM: [e. g. 16GB, 32GB, 64GB, ...] 64 GB

### Checklist:

- [ x] I have read the contribution guidelines.
- [x ] This is not a bug, crash or generic issue.

**Comment by Artoria2e5** [comment]
Uh here's the thing. You're supposed to read the readme.txt in the test zip folder and upload what's in the result folders.

(The readme forgot to mention one thing: you can't quite upload the zip file with the h264/h265 included to GitHub because they are too large to fit in the 25M limit. Delete those files before you zip.)

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
