### ISSUE TITLE
32-Bit is broken, unexpected return values from VCE

### ISSUE THREAD

**Issue by TUTCMO** [Xaymar/OBS-AMD-Advanced-Media-Framework#5]
[Crash 2016-07-31 11-45-57.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392508/Crash.2016-07-31.11-45-57.txt)

**Comment by Xaymar** [comment]
Please include the latest log file from OBS, if it generated one.

**Comment by TUTCMO** [comment]
[2016-07-31 10-50-51.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392523/2016-07-31.10-50-51.txt)

@Xaymar Here you are.

**Comment by Xaymar** [comment]
```
11:44:48.346: [AMF_Encoder::h264] Create: Initialization Request...
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_USAGE' to '2', result: (null) (206139504).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_QUALITY_PRESET' to '2', result: (null) (206158080).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_FRAMESIZE.X' to '1920', result: (null) (206148792).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_FRAMESIZE.Y' to '1080', result: (null) (206148792).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_FRAMERATE.Num' to '60', result: (null) (206158080).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_FRAMERATE.Den' to '1', result: (null) (206158080).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_PROFILE' to '100', result: (null) (206156016).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_PROFILE_LEVEL' to '51', result: (null) (206139504).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_SCANTYPE' to '0', result: (null) (206149824).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD' to '3', result: (null) (206139504).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_RATE_CONTROL_SKIP_FRAME_ENABLE' to 'false', result: AMF_OK (0).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_FILLER_DATA_ENABLE' to 'true', result: AMF_OK (0).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_GOP_SIZE' to '30', result: (null) (206139504).
11:44:48.373: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_INITIAL_VBV_BUFFER_FULLNESS' to '64', result: (null) (206139504).
11:44:48.374: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_TARGET_BITRATE' to '10000', result: (null) (206143632).
11:44:48.374: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_MOTION_HALF_PIXEL' to 'true', result: AMF_OK (0).
11:44:48.374: [AMF_Encoder::h264] Attempted to set property 'AMF_VIDEO_ENCODER_MOTION_QUARTERPIXEL' to 'true', result: AMF_OK (0).
11:44:48.381: [AMF_Encoder::h264] Create: Request completed.
```

I have never seen VCE return these values, those don't match any enumeration value. Make sure your GPU isn't overheating, is at stock(reference) clock speeds and try again.

**Comment by TUTCMO** [comment]
@Xaymar 

It isn't overheating and is at stock speeds.

I have the power limit in AB set to +50 and have made a custom fan curve. That's all I've done to it.

**Comment by Xaymar** [comment]
Then I don't know, I've never seen those values be returned - especially on critical values, normally it shouldn't even start up.

**Comment by TUTCMO** [comment]
@Xaymar 

Shucks

I'll give it another go later and see what happens.

**Comment by Xaymar** [comment]
Test with 1.1.2 please. If this still doesn't work, I'm gonna need the following:
- Full Hardware Specs
- OBS Studio version
- AMD Driver version
- Is the newest VS2015 redist installed?
- Latest log file and crash log

**Comment by Cruyelo** [comment]
Since this is the same issue I had:
Windows 10 Pro 64 bits - Insider Build - Build 14388.0
Intel i5-4690k overclocked to 4.3ghz.
16gb ram DDR3
MSI R9 390

OBS Studio 0.15.2 with plugin 1.1.2

AMD Driver 16.7.3

Newest VS2015 redist is installed. (I tried just in case, it gives me an error saying it already is installed)

By the way, I don't know if this is relevant, but the first log for OBS Studio doesn't talk about "required module function.... loading of module failed". Every log that came after that first launch does.

Latest logs, crashed after 21sec recording of desktop:
[Crash 2016-07-31 15-56-54.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392605/Crash.2016-07-31.15-56-54.txt)
[2016-07-31 15-56-21.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392606/2016-07-31.15-56-21.txt)

**Comment by Xaymar** [comment]
You should actually be using 64-bit, not 32-bit. I see that both of you are using the 32-bit version.

**Comment by Xaymar** [comment]
Further testing revealed that this only happens with the 32-bit version.

**Comment by TUTCMO** [comment]
@Xaymar 

I upgraded to the 64 bit version of 1.1.2 and got another crash.

I didn't have any trouble until I hit my hotkey for stop recording and noticed that the stop recording button in OBS said "Attempting to stop recording." I thought that was strange, so I hit alt+tab to leave my game and take a closer look. That's when I noticed the crash notification.

IDK if it happened when I hit my hotkey for stop recording or alt+tab.
[Crash 2016-07-31 16-38-06.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392630/Crash.2016-07-31.16-38-06.txt)
[2016-07-31 16-35-31.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392631/2016-07-31.16-35-31.txt)

Specs:
i7 4790K
ASUS Z97-A USB 3.1
EVGA Superclocked DDR3 1600 Mhz 16 GB
Sapphire R9 Nano
Windows 10 64 bit
Radeon Software version 16.7.3
OBS Studio version 0.15.2

IDK if the latest version of VS2015 is installed. Which one would I install, the x64 version or the x86 version?

**Comment by Cruyelo** [comment]
I made multiple tests and while I had another crash, I think it was simply because I was screwing around a little too much with the settings. Other than that, it seems to be working for now, but I've only done short tests (30 seconds to 60 seconds). 64 bits seem to have fixed the issue for me, thanks!

With that said, I have another issue, but I don't know if it's because I know very little about recording software or if it's an issue with OBS Studio. So I figured I would ask before creating a separate bug report:
- If I record with Rate Control Method at "Constrained QP" or "From Preset & Usage", the video quality of the recording is excellent. If I pick anything else, the quality is horrible and the file size very small. It doesn't matter if I pick a higher bitrate or anything, the quality is just terrible.
  Edit: From Preset & Usage doesn't seem to look better when I modify the bitrate. Constrained QP seems to work fine overall.

I picked my settings based on what you've shown on Reddit. Should I create a separate bug report? Or am I just dumb and missing an obvious mistake?

**Comment by Xaymar** [comment]
If you're typing in bitrate in kbit instead of bit, try multiplying by 1000! Then they start working.

**Comment by Cruyelo** [comment]
I was doing tests from 10 000 bits to 40 000 bits. But regardless of what I write (for quality/bits), Constant Bitrate and both forms of VBR have very very low quality in the final video. A 30 second clips is around 2mb.

I can make a new thread if this sounds like a proper issue.

**Comment by Xaymar** [comment]
Well, it's not a proper issue per-se. 10000 bits is 10kbit, that's almost nothing. Try 10000000 bits instead, which is 10mbit!

**Comment by Cruyelo** [comment]
Ah, alright. Yeah, now they all work fine. Thanks!

**Comment by TUTCMO** [comment]
I was just able to record a video w/o crashing.

Granted, it was only about two minutes long. I'll try recording a longer video and report back.

**Comment by TUTCMO** [comment]
@Xaymar 

So I just recorded for nearly twenty minutes, over one GB of video, and didn't have a crash.

It seems to be in working order now.

**Comment by Xaymar** [comment]
@TUTCMO 

32-Bit or 64-Bit?

**Comment by TUTCMO** [comment]
The latter.

I forgot to include my drives earlier when detailing my hardware specs.

Sandisk Extreme Pro 240 GB (This is where I record to)
Samsung 850 EVO 500 GB (This is my game drive)
Western Digital Caviar Blue 1 TB

I think that crash I had just after upgrading to the 64 bit version of 1.1.2 was fluke.

**Comment by Xaymar** [comment]
AMD_Robert talked about a new SDK being made, that could potentially fix this. I don't know when it's out or how hard it'll be to port over to, but I'll try.

**Comment by TUTCMO** [comment]
@Xaymar 

We appreciate your efforts. Keep up the good work.

**Comment by Xaymar** [comment]
I haven't observed this happening in 1.2.0 now, so closing.
