### ISSUE TITLE
AMF - Encoder Stuck / Crashed

### ISSUE THREAD

**Issue by locodicegr** [Xaymar/OBS-AMD-Advanced-Media-Framework#81]
Clean install of obs (64bit) & rc2 
i record redout game very well but after that, some games (phantaruk/Pollen) have the ''stopping recording'' problem,
here are all the logs from todays session's some are ok and others have the stopping recording problem, i dont remeber what is what, lol.

Simple Encoder / Recording preset / All default always i dont mess with anything / Mkv / R9 380 4G (stock)

[2016-09-11 10-34-13.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465812/2016-09-11.10-34-13.txt)
[2016-09-11 08-58-51.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465811/2016-09-11.08-58-51.txt)
[2016-09-11 09-18-28.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465813/2016-09-11.09-18-28.txt)
[2016-09-11 09-38-17.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465814/2016-09-11.09-38-17.txt)
[2016-09-11 10-03-34.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465815/2016-09-11.10-03-34.txt)
[2016-09-11 10-21-58.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465816/2016-09-11.10-21-58.txt)
[2016-09-11 10-27-46.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465817/2016-09-11.10-27-46.txt)

**Comment by Xaymar** [comment]
Encoder is overloaded and does an emergency quit to not end up eating up all memory. Also the stopping recording thing is a OBS issue, I'm not sure how many times I have to repeat that.

You can try lowering the Minimum QP value to 0, reducing the buffer size, using CQP instead of VBR_LAT to fix the overloaded issue.

### 2016-09-11 10-34-13, 2016-09-11 08-58-51, 2016-09-11 09-18-28, 2016-09-11 09-38-17

No Issue here.

### 2016-09-11 10-03-34

```
10:11:44.394: [AMF Encoder] <AMFEncoder::VCE::GetOutput> Resized Packet Buffer to 65536.
10:12:34.842: [AMF Encoder] <Plugin::AMD::VCEEncoder::SendInput> Input Queue is full, aborting...
10:12:34.842: [AMF Encoder] <AMFEncoder::H264SimpleInterface::~H264SimpleInterface> Finalizing...
10:12:35.317: [AMF Encoder] <AMFEncoder::H264SimpleInterface::~H264SimpleInterface> Complete.
```

### 2016-09-11 10-21-58

```
10:22:08.771: [AMF Encoder] <AMFEncoder::VCE::GetOutput> Resized Packet Buffer to 65536.
10:23:02.871: [AMF Encoder] <Plugin::AMD::VCEEncoder::SendInput> Input Queue is full, aborting...
10:23:02.871: [AMF Encoder] <AMFEncoder::H264SimpleInterface::~H264SimpleInterface> Finalizing...
10:23:03.632: [AMF Encoder] <AMFEncoder::H264SimpleInterface::~H264SimpleInterface> Complete.
```

### 2016-09-11 10-27-46

```
10:27:55.038: [AMF Encoder] <AMFEncoder::VCE::GetOutput> Resized Packet Buffer to 65536.
10:27:58.371: [AMF Encoder] <AMFEncoder::VCE::GetOutput> Resized Packet Buffer to 131072.
10:29:07.709: [AMF Encoder] <Plugin::AMD::VCEEncoder::SendInput> Input Queue is full, aborting...
10:29:07.709: [AMF Encoder] <AMFEncoder::H264SimpleInterface::~H264SimpleInterface> Finalizing...
10:29:08.284: [AMF Encoder] <AMFEncoder::H264SimpleInterface::~H264SimpleInterface> Complete.
```

**Comment by Xaymar** [comment]
Also, if it happens again I need a full process dump of obs*.exe.
1. Open Task Manager
2. Right click on obs32.exe or obs64.exe
3. Select "Create dump file"
4. Wait
5. A window should appear with a path to a .DMP file, compress and upload that file to a host. (mega.co.nz, mediafire.com, ... - anything with more than 200kbps download speed)
6. Put the link here

**Comment by jp9000** [comment]
If you are convinced that the program is getting stuck on "stopping recording" is an OBS problem, then please give me steps to replicate somehow.  I've never had that happen, but it's not impossible that it's the program's fault.  Get in contact with me if/when you have information I can use.  I've not heard of it happening with the other encoders to my knowledge.  It happens with streams because streams can get congested, but not with recording to my knowledge.

**Comment by Xaymar** [comment]
@jp9000 The description for obs_encoder_info->encode says the following:

```
     /**
     * Encodes frame(s), and outputs encoded packets as they become
     * available.
     *
     * @param       data             Data associated with this encoder
     *                               context
     * @param[in]   frame            Raw audio/video data to encode
     * @param[out]  packet           Encoder packet output, if any
     * @param[out]  received_packet  Set to true if a packet was received,
     *                               false otherwise
     * @return                       true if successful, false otherwise.
     */
```

I return false if an error occurs, which makes OBS shut down the encoder - but then the buttons will just get stuck on "Stopping <x>..." instead of an error message popping up. I could "solve" this by force crashing OBS - not ideal and could cause more issues than needed, especially for people recording to mp4.
1. https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/blob/master/enc-amf/Source/enc-h264-simple.cpp#L670
2. https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/blob/master/enc-amf/Source/enc-h264.cpp#L704

**Comment by Xaymar** [comment]
Reproduced an issue in which the GPU Encoder gets overloaded and just straight up gets stuck, rendering the system to stutter. Tracked under GPUOpen-LibrariesAndSDKs/AMF#19

**Comment by Tembew** [comment]
Is the stopping recording really an OBS issue or are you saying OBS saying that is the issue (because it could say something else)? I get the problem currently with your plugin but not with the VCE encoder that uses windows media foundation. With the same settings

**Comment by Xaymar** [comment]
The issue is with OBS, since it keeps displaying "Stopping x..." while it should show an error message and return to normal.

**Comment by Tembew** [comment]
ok. Glad to see the overload is getting looked at. 

Seems to be related to 3D graphics. In menus in rainbow six siege it seems to work fine most of the time. Crashes soon after the actual graphics start.

**Comment by PNunesDev** [comment]
Hi Xaymar, I have a HD 7850 and this issue, only happens to me when using your codec :|
So for now I am unable to record anything with it, I will try the tips of lowering the QP and everything like you did explained.

Cheers and keep up the good work
EDIT: I see you are looking to the issue with mikhail.
Good luck :)

**Comment by CKannas** [comment]
Hi Xaymar,

Yesterday (Sept. 18th) I was streaming using the 1.3.0rc3 version of the plugin with 16.9.1 Radeon drivers and 0.15.4 OBS Studio and I experienced 2 crashes , the first when OBS started to have huge delays I force quit and it crashed, and the second at the end of my stream when I try to exit OBS.
- Here are the log [2016-09-18 19-14-12.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/480024/2016-09-18.19-14-12.txt) and the crash log [Crash 2016-09-18 20-01-00.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/480025/Crash.2016-09-18.20-01-00.txt) of the 1st streaming attempt, which had huge delays and huge spikes [Bitrate Inspector](http://prntscr.com/cjsqlk).
- Here are the log [2016-09-18 20-01-17.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/480030/2016-09-18.20-01-17.txt) and the crash log [Crash 2016-09-18 22-49-04.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/480031/Crash.2016-09-18.22-49-04.txt) of the 2nd successfull streaming attempt [Bitrate Inspector](http://prntscr.com/cjsrlc).

For the first time I've noticed that the plugin reports the status of Input Queue. As you will see in the logs there are occasion the Input Queue is full and the encoder starts to drop frames.

#### Also a side note:
- I noticed that OBS was having higher CPU usage (15% - 20%) with rc3 than previous versions (max 15%).

Cheers and keep up the good work

**Comment by Xaymar** [comment]
@CKannas The CPU usage thing is due to the fact that I force the lowest possible Timer resolution again, since it seems to help with the timing issue that happened before - unfortunately this also means that something in OBS uses up more CPU, probably the Qt backend.

As for the delays, the only way to fix that is if I either drop all the current packets that are too much (possibly corrupting the stream) or get OBS to allow multiple packet returns and have OBS handle this issue instead.

**Comment by Xaymar** [comment]
Partially solved by reverting the OpenCL code @MikhailAMD told me to implement. Now the encoder sits at a much lower 1.7 - 3.0% cpu usage on top of the OBS usage itself. Unfortuantely, that brought back a stalling issue I have tracked here: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/22 https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/19

**Comment by Xaymar** [comment]
Reduced to a minimum in the latest release. Anything further now depends on AMD updating the runtime.
