### ISSUE TITLE
Stream has bitrate spikes at the start of the stream

### ISSUE THREAD

**Issue by CKannas** [Xaymar/OBS-AMD-Advanced-Media-Framework#82]
@Xaymar this is more of a question than an issue, because I think can be solved with some tweaking of the settings.

First of all I'd like to say that your plugin is getting better with every iteration. keep up the good work!

During the last two days of streaming since Sept. 10th I noticed that during the first 30 to 40 minutes of the stream, OBS output is unstable that is it has bitrate spikes of 4000kbps up to 7000kbps after that 30-40 minute mark the output is almost like a flat line around the specified bitrate target.

On Sept. 10th I used RC1 and on Sept. 11th RC2 versions of the plugin.
I use the Simple interface of AMF plugin  with the Twitch preset and the bitrate set to 1800kbps.

I'm thinking that during that phase starting phase of the stream the encoder gets overwhelmed and it needs some time to get to a good working state. I can understand that this might happen to a number of reasons which might be hard to trace down.
#### Questions:
- Which parameters influence more the the initialisation and the initial feed of data to the encoder?
- Is the encoder affected from graphics settings in games? 
- What can influence the behaviour of the VCE engine?

Latest log from last night's stream [2016-09-10 22-30-06.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/466005/2016-09-10.22-30-06.txt)

Thanks

**Comment by Xaymar** [comment]
1. Minimum QP, Maximum QP, Buffer Size, GOP Size - all of these can either negatively or positively influence how the encoder behaves. B-Pictures/B-Frames also have some effect, since when they aren't supported the GPU has to search for reference frames first.
2. DirectX12 and Vulkan games are heavy on the GPU side, so putting too much load on the GPU can break encoding - it is an OpenCL assisted task after all due to color conversion.
3. GPU Clock, VRAM Clock, Switching between GPU states, high CPU load, badly optimized DirectX12 games.

Also you are still on Driver 16.8.3 or before, please upgrade to 16.9.1.

**Comment by Xaymar** [comment]
No response from user, closing this now.
