### ISSUE TITLE
Set all streaming profiles to level 4.1 by default

### ISSUE THREAD

**Issue by nwgat** [Xaymar/OBS-AMD-Advanced-Media-Framework#84]
well if your streaming you want the broadest hardware decoding support and most hardware only does up to level 4.1

**Comment by Xaymar** [comment]
The issue with 4.1 is that 1280x720 at 60 fps requires at least 4.2. Otherwise you break the theorethical limits of the h264 stream. For most people that won't be an issue, but for those wanting that glorious 60 fps it is. I may have to add a "Default" option to Profile Level too, so it's calculated from the frame size and frame rate.

**Comment by nwgat** [comment]
atleast give the streamer a warning if they select above 4.1, that users might not be able to view it

**Comment by Xaymar** [comment]
Change to 4.1 is already implemented now for all streaming sites. People better get used to switching to 4.2 for 60 fps then.
